// Code generated by protoc-gen-go. DO NOT EDIT.
// source: maia.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ComponentType int32

const (
	ComponentType_ComponentType_NONE ComponentType = 0
	ComponentType_VIEW               ComponentType = 1
	ComponentType_CREATE             ComponentType = 2
	ComponentType_UPDATE             ComponentType = 3
	ComponentType_DELETE             ComponentType = 4
	ComponentType_IMPORT             ComponentType = 5
	ComponentType_EXPORT             ComponentType = 6
)

var ComponentType_name = map[int32]string{
	0: "ComponentType_NONE",
	1: "VIEW",
	2: "CREATE",
	3: "UPDATE",
	4: "DELETE",
	5: "IMPORT",
	6: "EXPORT",
}

var ComponentType_value = map[string]int32{
	"ComponentType_NONE": 0,
	"VIEW":               1,
	"CREATE":             2,
	"UPDATE":             3,
	"DELETE":             4,
	"IMPORT":             5,
	"EXPORT":             6,
}

func (x ComponentType) String() string {
	return proto.EnumName(ComponentType_name, int32(x))
}

func (ComponentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_015cf5a4c4f0380f, []int{0}
}

type FormType int32

const (
	FormType_FormatType_NONE FormType = 0
	FormType_HIDDEN          FormType = 1
	FormType_TEXT            FormType = 2
	FormType_TEXTAREA        FormType = 3
	FormType_SEARCH          FormType = 4
	FormType_TEL             FormType = 5
	FormType_URL             FormType = 6
	FormType_EMAIL           FormType = 7
	FormType_PASSWORD        FormType = 8
	FormType_DATETIME        FormType = 9
	FormType_DATE            FormType = 10
	FormType_TIME            FormType = 11
	FormType_NUMBER          FormType = 12
)

var FormType_name = map[int32]string{
	0:  "FormatType_NONE",
	1:  "HIDDEN",
	2:  "TEXT",
	3:  "TEXTAREA",
	4:  "SEARCH",
	5:  "TEL",
	6:  "URL",
	7:  "EMAIL",
	8:  "PASSWORD",
	9:  "DATETIME",
	10: "DATE",
	11: "TIME",
	12: "NUMBER",
}

var FormType_value = map[string]int32{
	"FormatType_NONE": 0,
	"HIDDEN":          1,
	"TEXT":            2,
	"TEXTAREA":        3,
	"SEARCH":          4,
	"TEL":             5,
	"URL":             6,
	"EMAIL":           7,
	"PASSWORD":        8,
	"DATETIME":        9,
	"DATE":            10,
	"TIME":            11,
	"NUMBER":          12,
}

func (x FormType) String() string {
	return proto.EnumName(FormType_name, int32(x))
}

func (FormType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_015cf5a4c4f0380f, []int{1}
}

type View struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Group                string   `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *View) Reset()         { *m = View{} }
func (m *View) String() string { return proto.CompactTextString(m) }
func (*View) ProtoMessage()    {}
func (*View) Descriptor() ([]byte, []int) {
	return fileDescriptor_015cf5a4c4f0380f, []int{0}
}

func (m *View) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_View.Unmarshal(m, b)
}
func (m *View) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_View.Marshal(b, m, deterministic)
}
func (m *View) XXX_Merge(src proto.Message) {
	xxx_messageInfo_View.Merge(m, src)
}
func (m *View) XXX_Size() int {
	return xxx_messageInfo_View.Size(m)
}
func (m *View) XXX_DiscardUnknown() {
	xxx_messageInfo_View.DiscardUnknown(m)
}

var xxx_messageInfo_View proto.InternalMessageInfo

func (m *View) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *View) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *View) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

type Component struct {
	Type                 ComponentType `protobuf:"varint,1,opt,name=type,proto3,enum=maia.ComponentType" json:"type,omitempty"`
	ImportOption         *ImportOption `protobuf:"bytes,2,opt,name=import_option,json=importOption,proto3" json:"import_option,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Component) Reset()         { *m = Component{} }
func (m *Component) String() string { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()    {}
func (*Component) Descriptor() ([]byte, []int) {
	return fileDescriptor_015cf5a4c4f0380f, []int{1}
}

func (m *Component) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component.Unmarshal(m, b)
}
func (m *Component) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component.Marshal(b, m, deterministic)
}
func (m *Component) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component.Merge(m, src)
}
func (m *Component) XXX_Size() int {
	return xxx_messageInfo_Component.Size(m)
}
func (m *Component) XXX_DiscardUnknown() {
	xxx_messageInfo_Component.DiscardUnknown(m)
}

var xxx_messageInfo_Component proto.InternalMessageInfo

func (m *Component) GetType() ComponentType {
	if m != nil {
		return m.Type
	}
	return ComponentType_ComponentType_NONE
}

func (m *Component) GetImportOption() *ImportOption {
	if m != nil {
		return m.ImportOption
	}
	return nil
}

type ImportOption struct {
	Diff                 bool     `protobuf:"varint,1,opt,name=diff,proto3" json:"diff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportOption) Reset()         { *m = ImportOption{} }
func (m *ImportOption) String() string { return proto.CompactTextString(m) }
func (*ImportOption) ProtoMessage()    {}
func (*ImportOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_015cf5a4c4f0380f, []int{2}
}

func (m *ImportOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportOption.Unmarshal(m, b)
}
func (m *ImportOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportOption.Marshal(b, m, deterministic)
}
func (m *ImportOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportOption.Merge(m, src)
}
func (m *ImportOption) XXX_Size() int {
	return xxx_messageInfo_ImportOption.Size(m)
}
func (m *ImportOption) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportOption.DiscardUnknown(m)
}

var xxx_messageInfo_ImportOption proto.InternalMessageInfo

func (m *ImportOption) GetDiff() bool {
	if m != nil {
		return m.Diff
	}
	return false
}

type Select struct {
	DefaultLabel         string   `protobuf:"bytes,1,opt,name=default_label,json=defaultLabel,proto3" json:"default_label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Select) Reset()         { *m = Select{} }
func (m *Select) String() string { return proto.CompactTextString(m) }
func (*Select) ProtoMessage()    {}
func (*Select) Descriptor() ([]byte, []int) {
	return fileDescriptor_015cf5a4c4f0380f, []int{3}
}

func (m *Select) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Select.Unmarshal(m, b)
}
func (m *Select) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Select.Marshal(b, m, deterministic)
}
func (m *Select) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Select.Merge(m, src)
}
func (m *Select) XXX_Size() int {
	return xxx_messageInfo_Select.Size(m)
}
func (m *Select) XXX_DiscardUnknown() {
	xxx_messageInfo_Select.DiscardUnknown(m)
}

var xxx_messageInfo_Select proto.InternalMessageInfo

func (m *Select) GetDefaultLabel() string {
	if m != nil {
		return m.DefaultLabel
	}
	return ""
}

type FormOption struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FormOption) Reset()         { *m = FormOption{} }
func (m *FormOption) String() string { return proto.CompactTextString(m) }
func (*FormOption) ProtoMessage()    {}
func (*FormOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_015cf5a4c4f0380f, []int{4}
}

func (m *FormOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FormOption.Unmarshal(m, b)
}
func (m *FormOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FormOption.Marshal(b, m, deterministic)
}
func (m *FormOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FormOption.Merge(m, src)
}
func (m *FormOption) XXX_Size() int {
	return xxx_messageInfo_FormOption.Size(m)
}
func (m *FormOption) XXX_DiscardUnknown() {
	xxx_messageInfo_FormOption.DiscardUnknown(m)
}

var xxx_messageInfo_FormOption proto.InternalMessageInfo

func (m *FormOption) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *FormOption) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Form struct {
	Type                 FormType `protobuf:"varint,1,opt,name=type,proto3,enum=maia.FormType" json:"type,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Icon                 string   `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Disabled             bool     `protobuf:"varint,5,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Min                  int32    `protobuf:"varint,10,opt,name=min,proto3" json:"min,omitempty"`
	Max                  int32    `protobuf:"varint,11,opt,name=max,proto3" json:"max,omitempty"`
	Len                  int32    `protobuf:"varint,12,opt,name=len,proto3" json:"len,omitempty"`
	Pattern              string   `protobuf:"bytes,13,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Format               string   `protobuf:"bytes,14,opt,name=format,proto3" json:"format,omitempty"`
	Nullable             bool     `protobuf:"varint,15,opt,name=nullable,proto3" json:"nullable,omitempty"`
	Default              *any.Any `protobuf:"bytes,20,opt,name=default,proto3" json:"default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Form) Reset()         { *m = Form{} }
func (m *Form) String() string { return proto.CompactTextString(m) }
func (*Form) ProtoMessage()    {}
func (*Form) Descriptor() ([]byte, []int) {
	return fileDescriptor_015cf5a4c4f0380f, []int{5}
}

func (m *Form) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Form.Unmarshal(m, b)
}
func (m *Form) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Form.Marshal(b, m, deterministic)
}
func (m *Form) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Form.Merge(m, src)
}
func (m *Form) XXX_Size() int {
	return xxx_messageInfo_Form.Size(m)
}
func (m *Form) XXX_DiscardUnknown() {
	xxx_messageInfo_Form.DiscardUnknown(m)
}

var xxx_messageInfo_Form proto.InternalMessageInfo

func (m *Form) GetType() FormType {
	if m != nil {
		return m.Type
	}
	return FormType_FormatType_NONE
}

func (m *Form) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Form) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Form) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Form) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *Form) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *Form) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *Form) GetLen() int32 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *Form) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *Form) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Form) GetNullable() bool {
	if m != nil {
		return m.Nullable
	}
	return false
}

func (m *Form) GetDefault() *any.Any {
	if m != nil {
		return m.Default
	}
	return nil
}

type Autocomplete struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Rpc                  string   `protobuf:"bytes,2,opt,name=rpc,proto3" json:"rpc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Autocomplete) Reset()         { *m = Autocomplete{} }
func (m *Autocomplete) String() string { return proto.CompactTextString(m) }
func (*Autocomplete) ProtoMessage()    {}
func (*Autocomplete) Descriptor() ([]byte, []int) {
	return fileDescriptor_015cf5a4c4f0380f, []int{6}
}

func (m *Autocomplete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Autocomplete.Unmarshal(m, b)
}
func (m *Autocomplete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Autocomplete.Marshal(b, m, deterministic)
}
func (m *Autocomplete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Autocomplete.Merge(m, src)
}
func (m *Autocomplete) XXX_Size() int {
	return xxx_messageInfo_Autocomplete.Size(m)
}
func (m *Autocomplete) XXX_DiscardUnknown() {
	xxx_messageInfo_Autocomplete.DiscardUnknown(m)
}

var xxx_messageInfo_Autocomplete proto.InternalMessageInfo

func (m *Autocomplete) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Autocomplete) GetRpc() string {
	if m != nil {
		return m.Rpc
	}
	return ""
}

type Table struct {
	Columns              []*TableColumn `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Pagination           bool           `protobuf:"varint,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Size                 int32          `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_015cf5a4c4f0380f, []int{7}
}

func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetColumns() []*TableColumn {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *Table) GetPagination() bool {
	if m != nil {
		return m.Pagination
	}
	return false
}

func (m *Table) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type TableColumn struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Field                string   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableColumn) Reset()         { *m = TableColumn{} }
func (m *TableColumn) String() string { return proto.CompactTextString(m) }
func (*TableColumn) ProtoMessage()    {}
func (*TableColumn) Descriptor() ([]byte, []int) {
	return fileDescriptor_015cf5a4c4f0380f, []int{8}
}

func (m *TableColumn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableColumn.Unmarshal(m, b)
}
func (m *TableColumn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableColumn.Marshal(b, m, deterministic)
}
func (m *TableColumn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableColumn.Merge(m, src)
}
func (m *TableColumn) XXX_Size() int {
	return xxx_messageInfo_TableColumn.Size(m)
}
func (m *TableColumn) XXX_DiscardUnknown() {
	xxx_messageInfo_TableColumn.DiscardUnknown(m)
}

var xxx_messageInfo_TableColumn proto.InternalMessageInfo

func (m *TableColumn) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *TableColumn) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type FileHeader struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64                `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	MimeType             *FileHeader_MIMEType `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	LastModified         *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FileHeader) Reset()         { *m = FileHeader{} }
func (m *FileHeader) String() string { return proto.CompactTextString(m) }
func (*FileHeader) ProtoMessage()    {}
func (*FileHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_015cf5a4c4f0380f, []int{9}
}

func (m *FileHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileHeader.Unmarshal(m, b)
}
func (m *FileHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileHeader.Marshal(b, m, deterministic)
}
func (m *FileHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileHeader.Merge(m, src)
}
func (m *FileHeader) XXX_Size() int {
	return xxx_messageInfo_FileHeader.Size(m)
}
func (m *FileHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_FileHeader.DiscardUnknown(m)
}

var xxx_messageInfo_FileHeader proto.InternalMessageInfo

func (m *FileHeader) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileHeader) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileHeader) GetMimeType() *FileHeader_MIMEType {
	if m != nil {
		return m.MimeType
	}
	return nil
}

func (m *FileHeader) GetLastModified() *timestamp.Timestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

type FileHeader_MIMEType struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileHeader_MIMEType) Reset()         { *m = FileHeader_MIMEType{} }
func (m *FileHeader_MIMEType) String() string { return proto.CompactTextString(m) }
func (*FileHeader_MIMEType) ProtoMessage()    {}
func (*FileHeader_MIMEType) Descriptor() ([]byte, []int) {
	return fileDescriptor_015cf5a4c4f0380f, []int{9, 0}
}

func (m *FileHeader_MIMEType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileHeader_MIMEType.Unmarshal(m, b)
}
func (m *FileHeader_MIMEType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileHeader_MIMEType.Marshal(b, m, deterministic)
}
func (m *FileHeader_MIMEType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileHeader_MIMEType.Merge(m, src)
}
func (m *FileHeader_MIMEType) XXX_Size() int {
	return xxx_messageInfo_FileHeader_MIMEType.Size(m)
}
func (m *FileHeader_MIMEType) XXX_DiscardUnknown() {
	xxx_messageInfo_FileHeader_MIMEType.DiscardUnknown(m)
}

var xxx_messageInfo_FileHeader_MIMEType proto.InternalMessageInfo

func (m *FileHeader_MIMEType) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *FileHeader_MIMEType) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type FileChunk struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileChunk) Reset()         { *m = FileChunk{} }
func (m *FileChunk) String() string { return proto.CompactTextString(m) }
func (*FileChunk) ProtoMessage()    {}
func (*FileChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_015cf5a4c4f0380f, []int{10}
}

func (m *FileChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileChunk.Unmarshal(m, b)
}
func (m *FileChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileChunk.Marshal(b, m, deterministic)
}
func (m *FileChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileChunk.Merge(m, src)
}
func (m *FileChunk) XXX_Size() int {
	return xxx_messageInfo_FileChunk.Size(m)
}
func (m *FileChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_FileChunk.DiscardUnknown(m)
}

var xxx_messageInfo_FileChunk proto.InternalMessageInfo

func (m *FileChunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type File struct {
	// Types that are valid to be assigned to File:
	//	*File_Header
	//	*File_Chunk
	File                 isFile_File `protobuf_oneof:"file"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_015cf5a4c4f0380f, []int{11}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

type isFile_File interface {
	isFile_File()
}

type File_Header struct {
	Header *FileHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type File_Chunk struct {
	Chunk *FileChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*File_Header) isFile_File() {}

func (*File_Chunk) isFile_File() {}

func (m *File) GetFile() isFile_File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *File) GetHeader() *FileHeader {
	if x, ok := m.GetFile().(*File_Header); ok {
		return x.Header
	}
	return nil
}

func (m *File) GetChunk() *FileChunk {
	if x, ok := m.GetFile().(*File_Chunk); ok {
		return x.Chunk
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*File) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _File_OneofMarshaler, _File_OneofUnmarshaler, _File_OneofSizer, []interface{}{
		(*File_Header)(nil),
		(*File_Chunk)(nil),
	}
}

func _File_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*File)
	// file
	switch x := m.File.(type) {
	case *File_Header:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Header); err != nil {
			return err
		}
	case *File_Chunk:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Chunk); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("File.File has unexpected type %T", x)
	}
	return nil
}

func _File_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*File)
	switch tag {
	case 1: // file.header
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FileHeader)
		err := b.DecodeMessage(msg)
		m.File = &File_Header{msg}
		return true, err
	case 2: // file.chunk
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FileChunk)
		err := b.DecodeMessage(msg)
		m.File = &File_Chunk{msg}
		return true, err
	default:
		return false, nil
	}
}

func _File_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*File)
	// file
	switch x := m.File.(type) {
	case *File_Header:
		s := proto.Size(x.Header)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *File_Chunk:
		s := proto.Size(x.Chunk)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

var E_Version = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         88040,
	Name:          "maia.version",
	Tag:           "bytes,88040,opt,name=version",
	Filename:      "maia.proto",
}

var E_View = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*View)(nil),
	Field:         88040,
	Name:          "maia.view",
	Tag:           "bytes,88040,opt,name=view",
	Filename:      "maia.proto",
}

var E_Component = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*Component)(nil),
	Field:         88040,
	Name:          "maia.component",
	Tag:           "bytes,88040,opt,name=component",
	Filename:      "maia.proto",
}

var E_FormOption = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*FormOption)(nil),
	Field:         88040,
	Name:          "maia.form_option",
	Tag:           "bytes,88040,opt,name=form_option",
	Filename:      "maia.proto",
}

var E_Required = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         88040,
	Name:          "maia.required",
	Tag:           "varint,88040,opt,name=required",
	Filename:      "maia.proto",
}

var E_Form = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Form)(nil),
	Field:         88050,
	Name:          "maia.form",
	Tag:           "bytes,88050,opt,name=form",
	Filename:      "maia.proto",
}

var E_Table = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Table)(nil),
	Field:         88051,
	Name:          "maia.table",
	Tag:           "bytes,88051,opt,name=table",
	Filename:      "maia.proto",
}

var E_Autocomplete = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Autocomplete)(nil),
	Field:         88052,
	Name:          "maia.autocomplete",
	Tag:           "bytes,88052,opt,name=autocomplete",
	Filename:      "maia.proto",
}

var E_Select = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*Select)(nil),
	Field:         88040,
	Name:          "maia.select",
	Tag:           "bytes,88040,opt,name=select",
	Filename:      "maia.proto",
}

var E_Label = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         88040,
	Name:          "maia.label",
	Tag:           "bytes,88040,opt,name=label",
	Filename:      "maia.proto",
}

func init() {
	proto.RegisterEnum("maia.ComponentType", ComponentType_name, ComponentType_value)
	proto.RegisterEnum("maia.FormType", FormType_name, FormType_value)
	proto.RegisterType((*View)(nil), "maia.View")
	proto.RegisterType((*Component)(nil), "maia.Component")
	proto.RegisterType((*ImportOption)(nil), "maia.ImportOption")
	proto.RegisterType((*Select)(nil), "maia.Select")
	proto.RegisterType((*FormOption)(nil), "maia.FormOption")
	proto.RegisterType((*Form)(nil), "maia.Form")
	proto.RegisterType((*Autocomplete)(nil), "maia.Autocomplete")
	proto.RegisterType((*Table)(nil), "maia.Table")
	proto.RegisterType((*TableColumn)(nil), "maia.TableColumn")
	proto.RegisterType((*FileHeader)(nil), "maia.FileHeader")
	proto.RegisterType((*FileHeader_MIMEType)(nil), "maia.FileHeader.MIMEType")
	proto.RegisterType((*FileChunk)(nil), "maia.FileChunk")
	proto.RegisterType((*File)(nil), "maia.File")
	proto.RegisterExtension(E_Version)
	proto.RegisterExtension(E_View)
	proto.RegisterExtension(E_Component)
	proto.RegisterExtension(E_FormOption)
	proto.RegisterExtension(E_Required)
	proto.RegisterExtension(E_Form)
	proto.RegisterExtension(E_Table)
	proto.RegisterExtension(E_Autocomplete)
	proto.RegisterExtension(E_Select)
	proto.RegisterExtension(E_Label)
}

func init() { proto.RegisterFile("maia.proto", fileDescriptor_015cf5a4c4f0380f) }

var fileDescriptor_015cf5a4c4f0380f = []byte{
	// 1130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x56, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x8e, 0x24, 0x52, 0x87, 0x91, 0x6c, 0xf3, 0xdf, 0x18, 0x01, 0x63, 0xfc, 0x4d, 0x14, 0xe6,
	0x22, 0x41, 0x8a, 0xc8, 0x80, 0x5a, 0xb4, 0x8d, 0x7a, 0x11, 0xc8, 0x16, 0x0d, 0x0b, 0xb0, 0x6c,
	0x63, 0x2d, 0xdb, 0x41, 0x6f, 0x0c, 0x9a, 0x5c, 0xc9, 0x8b, 0xf0, 0x54, 0x1e, 0xdc, 0xb8, 0x4f,
	0xd4, 0xbb, 0xbe, 0x45, 0x5f, 0xa4, 0x37, 0xbd, 0x6e, 0xfb, 0x00, 0xc5, 0xec, 0x2e, 0x65, 0x4a,
	0x32, 0xe0, 0x2b, 0x7d, 0x73, 0xfa, 0x66, 0x76, 0x76, 0x38, 0x2b, 0x80, 0xc0, 0xe1, 0x4e, 0x2f,
	0x4e, 0xa2, 0x2c, 0x22, 0x1a, 0xe2, 0x9d, 0xee, 0x3c, 0x8a, 0xe6, 0x3e, 0xdb, 0x15, 0xba, 0xeb,
	0x7c, 0xb6, 0xeb, 0xb1, 0xd4, 0x4d, 0x78, 0x9c, 0x45, 0x89, 0xf4, 0xdb, 0x79, 0xbe, 0xea, 0xe1,
	0x84, 0x77, 0xca, 0xf4, 0x72, 0xd5, 0x94, 0xf1, 0x80, 0xa5, 0x99, 0x13, 0xc4, 0xd2, 0xc1, 0xda,
	0x03, 0xed, 0x82, 0xb3, 0x5f, 0xc8, 0x26, 0x54, 0xb9, 0x67, 0x56, 0xba, 0x95, 0xb7, 0x2d, 0x5a,
	0xe5, 0x1e, 0xd9, 0x06, 0x3d, 0xe3, 0x99, 0xcf, 0xcc, 0xaa, 0x50, 0x49, 0x01, 0xb5, 0xf3, 0x24,
	0xca, 0x63, 0xb3, 0x26, 0xb5, 0x42, 0xb0, 0x02, 0x68, 0xed, 0x47, 0x41, 0x1c, 0x85, 0x2c, 0xcc,
	0xc8, 0x1b, 0xd0, 0xb2, 0xbb, 0x98, 0x09, 0xaa, 0xcd, 0xfe, 0xd3, 0x9e, 0x38, 0xcf, 0xc2, 0x3c,
	0xbd, 0x8b, 0x19, 0x15, 0x0e, 0xe4, 0x7b, 0xd8, 0xe0, 0x41, 0x1c, 0x25, 0xd9, 0x55, 0x14, 0x67,
	0x3c, 0x0a, 0x45, 0xa6, 0x76, 0x9f, 0xc8, 0x88, 0xb1, 0x30, 0x9d, 0x08, 0x0b, 0xed, 0xf0, 0x92,
	0x64, 0x59, 0xd0, 0x29, 0x5b, 0x09, 0x01, 0xcd, 0xe3, 0xb3, 0x99, 0xc8, 0xd8, 0xa4, 0x02, 0x5b,
	0xef, 0xa1, 0x7e, 0xc6, 0x7c, 0xe6, 0x66, 0xe4, 0x35, 0x6c, 0x78, 0x6c, 0xe6, 0xe4, 0x7e, 0x76,
	0xe5, 0x3b, 0xd7, 0xcc, 0x57, 0x67, 0xec, 0x28, 0xe5, 0x11, 0xea, 0xac, 0x11, 0xc0, 0x41, 0x94,
	0x04, 0x8a, 0x70, 0x71, 0xf6, 0x4a, 0xf9, 0xec, 0x5d, 0x68, 0x17, 0x9d, 0x2f, 0xaa, 0x6d, 0xd1,
	0xb2, 0xca, 0xfa, 0xa3, 0x0a, 0x1a, 0xd2, 0x10, 0x6b, 0xa9, 0x07, 0x9b, 0xf2, 0x44, 0x68, 0x29,
	0x1d, 0x7f, 0x1b, 0x74, 0x59, 0x8f, 0x6a, 0xb0, 0x10, 0x56, 0x93, 0xd4, 0xd6, 0x92, 0xe0, 0x69,
	0xb9, 0x1b, 0x85, 0xa6, 0x26, 0x4c, 0x02, 0x93, 0x1d, 0x68, 0x7a, 0x3c, 0x75, 0xae, 0x7d, 0xe6,
	0x99, 0xba, 0xe8, 0xc2, 0x42, 0x26, 0x06, 0xd4, 0x02, 0x1e, 0x9a, 0xd0, 0xad, 0xbc, 0xd5, 0x29,
	0x42, 0xa1, 0x71, 0xbe, 0x98, 0x6d, 0xa5, 0x71, 0xbe, 0xa0, 0xc6, 0x67, 0xa1, 0xd9, 0x91, 0x1a,
	0x9f, 0x85, 0xc4, 0x84, 0x46, 0xec, 0x64, 0x19, 0x4b, 0x42, 0x73, 0x43, 0x24, 0x2a, 0x44, 0xf2,
	0x0c, 0xea, 0xb3, 0x28, 0x09, 0x9c, 0xcc, 0xdc, 0x14, 0x06, 0x25, 0x61, 0x0d, 0x61, 0xee, 0xfb,
	0x98, 0xd4, 0xdc, 0x92, 0x35, 0x14, 0x32, 0xe9, 0x41, 0x43, 0xb5, 0xdb, 0xdc, 0x16, 0x97, 0xbc,
	0xdd, 0x93, 0x73, 0xd9, 0x2b, 0xe6, 0xb2, 0x37, 0x0c, 0xef, 0x68, 0xe1, 0x64, 0x0d, 0xa0, 0x33,
	0xcc, 0xb3, 0xc8, 0x8d, 0x82, 0xd8, 0x67, 0x19, 0xc3, 0x6a, 0x52, 0x96, 0xdc, 0x72, 0xb7, 0xb8,
	0x92, 0x42, 0xc4, 0xca, 0x93, 0xd8, 0x55, 0x3d, 0x44, 0x68, 0xdd, 0x80, 0x3e, 0x15, 0x49, 0xbf,
	0x86, 0x86, 0x1b, 0xf9, 0x79, 0x10, 0xa6, 0x66, 0xa5, 0x5b, 0x7b, 0xdb, 0xee, 0xff, 0x4f, 0xde,
	0x83, 0xb0, 0xee, 0x0b, 0x0b, 0x2d, 0x3c, 0xc8, 0x0b, 0x80, 0xd8, 0x99, 0xf3, 0xd0, 0x59, 0xdc,
	0x6d, 0x93, 0x96, 0x34, 0xd8, 0xf5, 0x94, 0xff, 0xca, 0xc4, 0x85, 0xe8, 0x54, 0x60, 0xeb, 0x03,
	0xb4, 0x4b, 0x5c, 0xf7, 0x17, 0x5a, 0x29, 0x5f, 0xe8, 0x36, 0xe8, 0x33, 0xce, 0x7c, 0xaf, 0xb8,
	0x66, 0x21, 0x58, 0x7f, 0x56, 0x00, 0x0e, 0xb8, 0xcf, 0x0e, 0x99, 0xe3, 0xb1, 0x04, 0xd9, 0x43,
	0x27, 0x28, 0x0e, 0x27, 0xf0, 0x22, 0x23, 0xc6, 0xd5, 0x64, 0x46, 0xf2, 0x1d, 0xb4, 0x02, 0x1e,
	0xb0, 0x2b, 0x31, 0x5c, 0x35, 0xd1, 0xc9, 0xe7, 0x6a, 0xb8, 0x16, 0x64, 0xbd, 0xc9, 0x78, 0x62,
	0x8b, 0x39, 0x6b, 0xa2, 0x2f, 0x22, 0xf2, 0x11, 0x36, 0x7c, 0x27, 0xcd, 0xae, 0x82, 0xc8, 0xe3,
	0x33, 0xae, 0x86, 0xa4, 0xdd, 0xdf, 0x59, 0xbb, 0x85, 0x69, 0xb1, 0x1d, 0x68, 0x07, 0x03, 0x26,
	0xca, 0x7f, 0xe7, 0x5b, 0x68, 0x16, 0xb4, 0xd8, 0xf2, 0xcf, 0xec, 0x4e, 0xd5, 0x8a, 0x10, 0x47,
	0xe2, 0xd6, 0xf1, 0x73, 0x96, 0x9a, 0xd5, 0x6e, 0x0d, 0x47, 0x42, 0x4a, 0xd6, 0x4b, 0x68, 0x61,
	0x5d, 0xfb, 0x37, 0x79, 0xf8, 0x59, 0x7c, 0xa5, 0x4e, 0xe6, 0x88, 0xb8, 0x0e, 0x15, 0xd8, 0x72,
	0x41, 0x43, 0x07, 0xf2, 0x0e, 0xea, 0x37, 0xa2, 0x78, 0x61, 0x6d, 0xf7, 0x8d, 0xd5, 0x43, 0x1d,
	0x3e, 0xa1, 0xca, 0x83, 0xbc, 0x01, 0xdd, 0x45, 0x42, 0xb5, 0x2e, 0xb6, 0xee, 0x5d, 0x45, 0x9e,
	0xc3, 0x27, 0x54, 0xda, 0xf7, 0xea, 0xa0, 0xcd, 0xb8, 0xcf, 0xde, 0x05, 0xb0, 0xb1, 0xb4, 0x7e,
	0xc8, 0x33, 0x20, 0x4b, 0x8a, 0xab, 0xe3, 0x93, 0x63, 0xdb, 0x78, 0x42, 0x9a, 0xa0, 0x5d, 0x8c,
	0xed, 0x4b, 0xa3, 0x42, 0x00, 0xea, 0xfb, 0xd4, 0x1e, 0x4e, 0x6d, 0xa3, 0x8a, 0xf8, 0xfc, 0x74,
	0x84, 0xb8, 0x86, 0x78, 0x64, 0x1f, 0xd9, 0x53, 0xdb, 0xd0, 0x10, 0x8f, 0x27, 0xa7, 0x27, 0x74,
	0x6a, 0xe8, 0x88, 0xed, 0x4f, 0x02, 0xd7, 0xdf, 0xfd, 0x56, 0x81, 0x66, 0xf1, 0xa9, 0x93, 0xa7,
	0xb0, 0x75, 0x20, 0x3e, 0x8f, 0x72, 0x1e, 0x80, 0xfa, 0xe1, 0x78, 0x34, 0xb2, 0x8f, 0x8d, 0x0a,
	0xe6, 0x9c, 0xda, 0x9f, 0xa6, 0x46, 0x95, 0x74, 0xa0, 0x89, 0x68, 0x48, 0xed, 0xa1, 0xcc, 0x74,
	0x66, 0x0f, 0xe9, 0xfe, 0xa1, 0xa1, 0x91, 0x06, 0xd4, 0xa6, 0xf6, 0x91, 0xa1, 0x23, 0x38, 0xa7,
	0x47, 0x46, 0x9d, 0xb4, 0x40, 0xb7, 0x27, 0xc3, 0xf1, 0x91, 0xd1, 0xc0, 0xb0, 0xd3, 0xe1, 0xd9,
	0xd9, 0xe5, 0x09, 0x1d, 0x19, 0x4d, 0x94, 0xb0, 0xd4, 0xe9, 0x78, 0x62, 0x1b, 0x2d, 0x24, 0x17,
	0x85, 0x83, 0x48, 0x83, 0xba, 0x36, 0x12, 0x1f, 0x9f, 0x4f, 0xf6, 0x6c, 0x6a, 0x74, 0x06, 0x3f,
	0x40, 0xe3, 0x96, 0x25, 0x29, 0xce, 0xf7, 0xff, 0xd7, 0x46, 0x01, 0x3b, 0x2a, 0xf7, 0x61, 0x6a,
	0xfe, 0xf5, 0xbb, 0x2e, 0x3f, 0x3b, 0xe5, 0x3e, 0x18, 0x82, 0x76, 0x8b, 0xaf, 0xc6, 0xcb, 0xb5,
	0xb0, 0x33, 0xf9, 0x61, 0x2e, 0x47, 0xb6, 0xfb, 0x20, 0xaf, 0x09, 0x9f, 0x1a, 0x2a, 0x42, 0x07,
	0x27, 0xd0, 0x72, 0x17, 0x8f, 0xc6, 0x8b, 0x35, 0x9e, 0x09, 0xcb, 0x6e, 0x22, 0x6f, 0x95, 0x66,
	0x6b, 0xe5, 0x39, 0xa1, 0xf7, 0x1c, 0x83, 0x29, 0xb4, 0x71, 0x15, 0xa9, 0xd7, 0xe4, 0x81, 0xd2,
	0x26, 0x2c, 0x4d, 0x9d, 0xf9, 0x5a, 0x69, 0xc6, 0xfd, 0x7a, 0x56, 0xcf, 0x0d, 0xcc, 0x16, 0x78,
	0xf0, 0x23, 0x34, 0x13, 0xf6, 0x73, 0xce, 0x13, 0xe6, 0x91, 0xaf, 0x1e, 0x68, 0x12, 0xf3, 0x57,
	0x8a, 0x6c, 0xd2, 0x45, 0xc0, 0xe0, 0x23, 0x68, 0x48, 0xf5, 0x58, 0xe0, 0xdf, 0xcb, 0x4d, 0xc2,
	0x4a, 0xa8, 0x08, 0x1c, 0xec, 0x81, 0x9e, 0x89, 0x65, 0xf6, 0x08, 0xc3, 0x3f, 0x8a, 0xa1, 0x5d,
	0x5a, 0x71, 0x54, 0x86, 0x0e, 0x2e, 0xa1, 0xe3, 0x94, 0x97, 0xe9, 0x23, 0x54, 0xff, 0x2a, 0x2a,
	0xf5, 0x0e, 0x97, 0xf7, 0x30, 0x5d, 0x22, 0x1a, 0x8c, 0xa0, 0x9e, 0xca, 0x37, 0x76, 0x7d, 0x7a,
	0xec, 0x30, 0x0f, 0x56, 0x1b, 0xdd, 0x91, 0x8c, 0xf2, 0x5d, 0xa6, 0x2a, 0x76, 0xf0, 0x41, 0xad,
	0x4d, 0xf2, 0xea, 0x41, 0x92, 0x0b, 0x5c, 0x25, 0xab, 0x73, 0x28, 0x23, 0xf6, 0x5e, 0xff, 0xf4,
	0x6a, 0xce, 0xb3, 0x9b, 0xfc, 0xba, 0xe7, 0x46, 0xc1, 0xee, 0x3c, 0x89, 0xdd, 0xf7, 0x6e, 0x9e,
	0x66, 0x51, 0xb0, 0x8b, 0x89, 0xd4, 0x7f, 0x9e, 0xba, 0xf8, 0xf9, 0xe6, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x31, 0x7b, 0xcb, 0xf9, 0x59, 0x09, 0x00, 0x00,
}
